services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx
    env_file: .env
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "443:443"
    volumes:
      - wordpressV:/var/www/html
    networks:
      - my_network
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "wget --no-check-certificate --spider -q https://localhost/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    container_name: mariadb
    image: mariadb
    networks:
      - my_network
    volumes:
      - mariadbV:/var/lib/mysql
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    container_name: wordpress
    image: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    restart: on-failure
    volumes: 
      - wordpressV:/var/www/html
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -q '[p]hp-fpm' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  my_network:
    driver: bridge

volumes:
  wordpressV:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/wordpress
  mariadbV:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/mariadb